"""Add replied_user_id to action_comments

Revision ID: 024cf4b128ef
Revises: 8cb7ad9cac1e
Create Date: 2025-05-14 14:10:37.395438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024cf4b128ef'
down_revision = '8cb7ad9cac1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['replied_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replied_user_id')

    # ### end Alembic commands ###
