"""Add UserTopicPosition table

Revision ID: 02c2a75d6c62
Revises: f738a196378f
Create Date: 2025-04-23 00:45:45.722806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c2a75d6c62'
down_revision = 'f738a196378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topic_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='fk_user_topic_positions_topic_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_topic_positions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_position')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_chat_room_id')
        batch_op.drop_index('ix_chat_messages_user_id')

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('ix_chat_rooms_name')
        batch_op.drop_index('ix_chat_rooms_topic_id')

    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.create_index('ix_chat_rooms_topic_id', ['topic_id'], unique=False)
        batch_op.create_index('ix_chat_rooms_name', ['name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_chat_messages_chat_room_id', ['chat_room_id'], unique=False)

    op.drop_table('user_topic_positions')
    # ### end Alembic commands ###
