"""Add topic_id to Article model

Revision ID: 070d42a75cb6
Revises: fe1db4ebe43b
Create Date: 2025-04-17 21:10:00.197161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070d42a75cb6'
down_revision = 'fe1db4ebe43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_topic_id'))
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
