"""Add user_id to Article and remove author column

Revision ID: 09f6d4a82873
Revises: 976d9925cc19
Create Date: 2025-04-12 14:29:00.034191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f6d4a82873'
down_revision = '976d9925cc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # Add server_default='1' to handle existing rows
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='1')) 
        batch_op.create_index(batch_op.f('ix_articles_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_articles_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # Remove the server_default after adding the column (optional but good practice)
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_articles_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
