"""Add notifications table

Revision ID: 0ed6822d5e4c
Revises: 0aee116818c8
Create Date: 2025-05-22 02:04:36.380818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed6822d5e4c'
down_revision = '0aee116818c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_interactions', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='交互内容类型: article, post, action',
               existing_nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='内容ID',
               existing_nullable=False)
        batch_op.alter_column('interaction_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='交互类型: like, collect',
               existing_nullable=False)
        batch_op.drop_index('ix_global_interactions_combined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_interactions', schema=None) as batch_op:
        batch_op.create_index('ix_global_interactions_combined', ['user_id', 'content_type', 'content_id', 'interaction_type'], unique=True)
        batch_op.alter_column('interaction_type',
               existing_type=sa.VARCHAR(length=20),
               comment='交互类型: like, collect',
               existing_nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               comment='内容ID',
               existing_nullable=False)
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=20),
               comment='交互内容类型: article, post, action',
               existing_nullable=False)

    op.drop_table('notifications')
    # ### end Alembic commands ###
