"""Add RelationshipTopic model

Revision ID: 0fbbdf4cc9d0
Revises: 9e6a844f0c30
Create Date: 2025-04-23 14:38:30.870184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbbdf4cc9d0'
down_revision = '9e6a844f0c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_topics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_topics_slug'), ['slug'], unique=True)

    op.create_table('relationship_topic_participants',
    sa.Column('relationship_topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_topic_id'], ['relationship_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_topic_id', 'topic_id')
    )
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('relationship_topic_participants')
    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_relationship_topics_name'))

    op.drop_table('relationship_topics')
    # ### end Alembic commands ###
