"""add_post_id_to_comments_and_make_article_id_nullable

Revision ID: 0ff1134cb3e7
Revises: 0843a63951e9
Create Date: 2025-05-18 15:12:56.538278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff1134cb3e7'
down_revision = '0843a63951e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
