"""Add tags column to User model

Revision ID: 10c481e7aa9a
Revises: c34e8dd9f581
Create Date: 2025-04-21 17:10:25.618368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c481e7aa9a'
down_revision = 'c34e8dd9f581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
