"""Update Comment model for block comments on tools and articles

Revision ID: 1ccaca9f86e9
Revises: 37b9da42485f
Create Date: 2025-04-13 00:15:08.914497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccaca9f86e9'
down_revision = '37b9da42485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('block_identifier', sa.String(length=100), nullable=True))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_comments_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_block_identifier'), ['block_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_tool_id'), ['tool_id'], unique=False)
        batch_op.create_foreign_key(None, 'tools', ['tool_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_tool_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_block_identifier'))
        batch_op.drop_index(batch_op.f('ix_comments_article_id'))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('block_identifier')
        batch_op.drop_column('tool_id')

    # ### end Alembic commands ###
