"""Add Topic and TopicRelation models

Revision ID: 1cfb3b652750
Revises: 3dcfbeffdde4
Create Date: 2025-04-17 19:03:42.310460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfb3b652750'
down_revision = '3dcfbeffdde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('style_bgcolor', sa.String(length=20), nullable=True),
    sa.Column('style_fgcolor', sa.String(length=20), nullable=True),
    sa.Column('style_width', sa.Integer(), nullable=True),
    sa.Column('style_height', sa.Integer(), nullable=True),
    sa.Column('style_shape', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('topic_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_topic_id', sa.Integer(), nullable=False),
    sa.Column('target_topic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('style_animated', sa.Boolean(), nullable=True),
    sa.Column('style_thickness', sa.Integer(), nullable=True),
    sa.Column('style_color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_relations_source_topic_id'), ['source_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_relations_target_topic_id'), ['target_topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_relations_target_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_relations_source_topic_id'))

    op.drop_table('topic_relations')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_name'))

    op.drop_table('topics')
    # ### end Alembic commands ###
