"""add_on_delete_set_null_to_user_actions_original_action_id

Revision ID: 2281bae89647
Revises: 5ae7ba2f9ecc
Create Date: 2025-05-13 21:27:20.161137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2281bae89647'
down_revision = '5ae7ba2f9ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilibili_video_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_bilibili_video_assets_bvid')

    op.drop_table('post_bilibili_video_map')
    op.drop_table('article_bilibili_video_map')
    op.drop_table('bilibili_video_assets')
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_constraint('user_actions_original_action_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_actions', ['original_action_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_actions_original_action_id_fkey', 'user_actions', ['original_action_id'], ['id'])

    op.create_table('article_bilibili_video_map',
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bilibili_video_asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_bilibili_video_map_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bilibili_video_asset_id'], ['bilibili_video_assets.id'], name='article_bilibili_video_map_bilibili_video_asset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'bilibili_video_asset_id', name='article_bilibili_video_map_pkey')
    )
    op.create_table('post_bilibili_video_map',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bilibili_video_asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bilibili_video_asset_id'], ['bilibili_video_assets.id'], name='post_bilibili_video_map_bilibili_video_asset_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_bilibili_video_map_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'bilibili_video_asset_id', name='post_bilibili_video_map_pkey')
    )
    op.create_table('bilibili_video_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bvid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cover_cos_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('original_cover_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uploader', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bilibili_video_assets_pkey')
    )
    with op.batch_alter_table('bilibili_video_assets', schema=None) as batch_op:
        batch_op.create_index('ix_bilibili_video_assets_bvid', ['bvid'], unique=True)

    # ### end Alembic commands ###
