"""Add UserTopicPosition model

Revision ID: 2a8f6c140d6b
Revises: 02c2a75d6c62
Create Date: 2025-04-23 01:13:59.472396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8f6c140d6b'
down_revision = '02c2a75d6c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除对 paragraph_comments 表的修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)

    # 仅保留对 user_topic_positions 表的修改
    with op.batch_alter_table('user_topic_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('uq_user_topic_position', type_='unique')
        batch_op.create_unique_constraint('uix_user_topic_position', ['user_id', 'topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_topic_positions', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_topic_position', type_='unique')
        batch_op.create_unique_constraint('uq_user_topic_position', ['user_id', 'topic_id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # 移除对 paragraph_comments 表的修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True)

    # ### end Alembic commands ###
