"""Add ActionInteraction model and original_action_id to UserAction

Revision ID: 3dcfbeffdde4
Revises: 4587b8783bce
Create Date: 2025-04-17 12:24:16.749315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcfbeffdde4'
down_revision = '4587b8783bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['user_actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action_id', 'interaction_type', name='uq_user_action_interaction')
    )
    with op.batch_alter_table('action_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_interactions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_interactions_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_article_id', sa.Integer(), nullable=True),
    sa.Column('target_tool_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamics_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_article_id'), ['target_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_tool_id'), ['target_tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_action_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_actions_original_action_id'), ['original_action_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_actions', ['original_action_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_actions_original_action_id'))
        batch_op.drop_column('original_action_id')

    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamics_user_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_tool_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_article_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_action_type'))

    op.drop_table('dynamics')
    with op.batch_alter_table('action_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_interactions_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_action_interactions_action_id'))

    op.drop_table('action_interactions')
    # ### end Alembic commands ###
