"""Add relationship topics and tags models

Revision ID: 49a1b4633a22
Revises: 0fbbdf4cc9d0
Create Date: 2025-04-23 16:23:06.607893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a1b4633a22'
down_revision = '0fbbdf4cc9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_like')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_categories_name')
        batch_op.drop_index('ix_categories_slug')
        batch_op.create_unique_constraint('uq_categories_name', ['name'])
        batch_op.drop_column('slug')
        batch_op.drop_column('icon')

    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('relationship_topic_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('relationship_topic_participants_relationship_topic_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('relationship_topic_participants_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_relationship_topic_participants_topic_id', 'topics', ['topic_id'], ['id'])
        batch_op.create_foreign_key('fk_relationship_topic_participants_relationship_topic_id', 'relationship_topics', ['relationship_topic_id'], ['id'])

    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('ix_relationship_topics_name')
        batch_op.drop_index('ix_relationship_topics_slug')
        batch_op.create_unique_constraint('uq_relationship_topics_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_relationship_topics_slug', type_='unique')
        batch_op.create_index('ix_relationship_topics_slug', ['slug'], unique=True)
        batch_op.create_index('ix_relationship_topics_name', ['name'], unique=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('relation_type')

    with op.batch_alter_table('relationship_topic_participants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_relationship_topic_participants_topic_id', type_='foreignkey')
        batch_op.drop_constraint('fk_relationship_topic_participants_relationship_topic_id', type_='foreignkey')
        batch_op.create_foreign_key('relationship_topic_participants_topic_id_fkey', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('relationship_topic_participants_relationship_topic_id_fkey', 'relationship_topics', ['relationship_topic_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('role')

    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_categories_name', type_='unique')
        batch_op.create_index('ix_categories_slug', ['slug'], unique=True)
        batch_op.create_index('ix_categories_name', ['name'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('post_tags')
    op.drop_table('post_likes')
    op.drop_table('notifications')
    op.drop_table('tags')
    # ### end Alembic commands ###
