"""Add slug to Post model

Revision ID: 4d7b854fb79a
Revises: 7429b69b6528
Create Date: 2025-04-18 17:41:48.794169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7b854fb79a'
down_revision = '7429b69b6528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_article_id', sa.Integer(), nullable=True),
    sa.Column('target_tool_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamics_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_article_id'), ['target_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_tool_id'), ['target_tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamics_user_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_tool_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_article_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_action_type'))

    op.drop_table('dynamics')
    # ### end Alembic commands ###
