"""Add comments_count to UserAction model

Revision ID: 51c44cbd8817
Revises: 69b02cee4317
Create Date: 2025-05-12 15:46:45.975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c44cbd8817'
down_revision = '69b02cee4317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加带默认值的列
    op.add_column('user_actions', sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False))

    # 更新现有记录的评论数
    op.execute("""
        UPDATE user_actions 
        SET comments_count = COALESCE((
            SELECT COUNT(*) 
            FROM action_comments 
            WHERE action_comments.action_id = user_actions.id 
            AND action_comments.is_deleted = false
        ), 0)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_actions', 'comments_count')
    # ### end Alembic commands ###
