"""add_bilibili_video_assets_and_maps

Revision ID: 5ae7ba2f9ecc
Revises: b17984d4378e
Create Date: 2025-05-13 16:34:03.364651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae7ba2f9ecc'
down_revision = 'b17984d4378e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilibili_video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bvid', sa.String(length=32), nullable=False),
    sa.Column('cover_cos_url', sa.String(length=255), nullable=True),
    sa.Column('original_cover_url', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('uploader', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilibili_video_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilibili_video_assets_bvid'), ['bvid'], unique=True)

    op.create_table('article_bilibili_video_map',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('bilibili_video_asset_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bilibili_video_asset_id'], ['bilibili_video_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'bilibili_video_asset_id'),
    info={'bind_key': None}
    )
    op.create_table('post_bilibili_video_map',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('bilibili_video_asset_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bilibili_video_asset_id'], ['bilibili_video_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'bilibili_video_asset_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_bilibili_video_map')
    op.drop_table('article_bilibili_video_map')
    with op.batch_alter_table('bilibili_video_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilibili_video_assets_bvid'))

    op.drop_table('bilibili_video_assets')
    # ### end Alembic commands ###
