"""Add relationship_topic_id to Post model

Revision ID: 5d414d0e076e
Revises: 52fc5c13042b
Create Date: 2025-04-23 19:29:23.328416

"""
from alembic import op
import sqlalchemy as sa
# Remove unused import if cleaning up
# from sqlalchemy.dialects import postgresql 

# revision identifiers, used by Alembic.
revision = '5d414d0e076e'
down_revision = '52fc5c13042b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - KEEP ONLY NECESSARY ###
    print("Applying migration 5d414d0e076e: Add relationship_topic_id to posts table")
    
    # --- Start of intended changes --- 
    with op.batch_alter_table('posts', schema=None) as batch_op:
        print("Adding relationship_topic_id column to posts table.")
        batch_op.add_column(sa.Column('relationship_topic_id', sa.Integer(), nullable=True))
        print("Adding foreign key constraint fk_posts_relationship_topic_id.")
        # Explicitly name the foreign key
        batch_op.create_foreign_key('fk_posts_relationship_topic_id', 'relationship_topics', ['relationship_topic_id'], ['id']) 
    # --- End of intended changes --- 

    # --- Start of commented out UNINTENDED changes --- 
    # op.create_table('relationship_topic_participants', ...)
    # op.drop_table('post_likes')
    # op.drop_table('notifications')
    # with op.batch_alter_table('categories', ...):
    #     ...
    # with op.batch_alter_table('post_comments', ...):
    #     ...
    # with op.batch_alter_table('posts', ...): # Other post changes
    #     batch_op.alter_column('topic_id',...)
    #     batch_op.create_index(...)
    #     batch_op.drop_column('publication_status')
    #     ...
    # with op.batch_alter_table('relationship_topics', ...):
    #     ...
    # --- End of commented out UNINTENDED changes --- 

    print("Finished migration 5d414d0e076e.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - KEEP ONLY NECESSARY ###
    print("Reverting migration 5d414d0e076e: Remove relationship_topic_id from posts table")

    # --- Start of intended changes --- 
    with op.batch_alter_table('posts', schema=None) as batch_op:
        print("Dropping foreign key constraint fk_posts_relationship_topic_id.")
        # Use the correct name to drop the foreign key
        batch_op.drop_constraint('fk_posts_relationship_topic_id', type_='foreignkey')
        print("Dropping relationship_topic_id column from posts table.")
        batch_op.drop_column('relationship_topic_id')
    # --- End of intended changes --- 

    # --- Start of commented out UNINTENDED changes --- 
    # with op.batch_alter_table('relationship_topics', ...):
    #     ...
    # with op.batch_alter_table('posts', ...): # Other post changes
    #     ...
    # with op.batch_alter_table('post_comments', ...):
    #     ...
    # with op.batch_alter_table('categories', ...):
    #     ...
    # op.create_table('notifications', ...)
    # op.create_table('post_likes', ...)
    # op.drop_table('relationship_topic_participants')
    # --- End of commented out UNINTENDED changes --- 
    
    print("Finished reverting migration 5d414d0e076e.")
    # ### end Alembic commands ###
