"""添加文章和帖子交互表

Revision ID: 67efb3cb1912
Revises: 0ff1134cb3e7
Create Date: 2025-05-21 23:26:55.349102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67efb3cb1912'
down_revision = '0ff1134cb3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_user_id'), ['user_id'], unique=False)

    op.create_table('article_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', 'interaction_type', name='unique_article_interaction')
    )
    op.create_table('dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_article_id', sa.Integer(), nullable=True),
    sa.Column('target_tool_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamics_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_article_id'), ['target_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_target_tool_id'), ['target_tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamics_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', 'interaction_type', name='unique_post_interaction')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_comments_post_id')
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_post_id_fkey', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_comments_post_id', ['post_id'], unique=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('post_interactions')
    op.drop_table('feedback')
    with op.batch_alter_table('dynamics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamics_user_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_tool_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_target_article_id'))
        batch_op.drop_index(batch_op.f('ix_dynamics_action_type'))

    op.drop_table('dynamics')
    op.drop_table('article_interactions')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_answers_created_at'))
        batch_op.drop_index(batch_op.f('ix_answers_article_id'))

    op.drop_table('answers')
    # ### end Alembic commands ###
