"""add_ondelete_cascade_to_comment_likes_comment_id

Revision ID: 69b02cee4317
Revises: 800d0c54a671
Create Date: 2025-05-09 13:58:27.036492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b02cee4317'
down_revision = '800d0c54a671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint('comment_likes_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_likes_comment_id_fkey', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
