"""Add soft delete fields to ActionComment

Revision ID: 6a2e008cb18e
Revises: fe899c2d6bc2
Create Date: 2025-04-25 17:30:14.440633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2e008cb18e'
down_revision = 'fe899c2d6bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- 修改开始 ---
    # 1. 添加 is_deleted 列，暂时允许 NULL
    op.add_column('action_comments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # 2. 将现有行的 is_deleted 更新为 False
    op.execute('UPDATE action_comments SET is_deleted = FALSE WHERE is_deleted IS NULL')
    # 3. 将 is_deleted 列修改为 NOT NULL
    op.alter_column('action_comments', 'is_deleted', nullable=False, server_default=sa.false()) # 添加 server_default 确保新行也有默认值

    # 4. 添加 original_content 列 (这个允许 NULL，所以可以直接添加)
    op.add_column('action_comments', sa.Column('original_content', sa.Text(), nullable=True))
    # --- 修改结束 ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.drop_column('original_content')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
