"""Add is_deleted column to comments table

Revision ID: 70a1186f31c1
Revises: abcdef123456
Create Date: 2025-04-30 13:52:18.816013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a1186f31c1'
down_revision = 'abcdef123456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_chat_room_id')
        batch_op.drop_index('ix_chat_messages_created_at')
        batch_op.drop_index('ix_chat_messages_user_id')

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint('chat_rooms_topic_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_rooms_relationship_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'relationship_topics', ['relationship_topic_id'], ['id'])

    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('ix_relationship_topics_slug')
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('topics_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_name'))
        batch_op.create_unique_constraint('topics_name_key', ['name'])
        batch_op.alter_column('slug',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_relationship_topics_slug', ['slug'], unique=True)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_rooms_relationship_topic_id_fkey', 'relationship_topics', ['relationship_topic_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('chat_rooms_topic_id_fkey', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_chat_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_chat_messages_chat_room_id', ['chat_room_id'], unique=False)

    # ### end Alembic commands ###
