"""Add Post model and remove topic_id from Article

Revision ID: 7429b69b6528
Revises: 070d42a75cb6
Create Date: 2025-04-18 15:56:41.579213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7429b69b6528'
down_revision = '070d42a75cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    # --- 数据迁移开始 ---
    # 注意：这里的字段名需要和你的 Post 和 Article 模型完全对应
    # 假设 Post 模型中需要的字段在 Article 中都存在或有默认值
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # 1. 将 articles 表中是帖子的数据复制到 posts 表
    op.execute("""
        INSERT INTO posts (id, title, content, user_id, topic_id, cover_image, is_published, view_count, created_at, updated_at)
        SELECT id, title, content, user_id, topic_id, cover_image, is_published, view_count, created_at, updated_at
        FROM articles
        WHERE topic_id IS NOT NULL
    """)

    # 2. 删除引用这些文章的评论
    op.execute("""
        DELETE FROM comments
        WHERE article_id IN (SELECT id FROM articles WHERE topic_id IS NOT NULL)
    """)

    # 3. 删除引用这些文章的回答
    #    (假设 Answer 模型存在且有 article_id 外键)
    op.execute("""
        DELETE FROM answers
        WHERE article_id IN (SELECT id FROM articles WHERE topic_id IS NOT NULL)
    """)

    # 4. 从 articles 表中删除已迁移的数据
    op.execute("""
        DELETE FROM articles
        WHERE topic_id IS NOT NULL
    """)
    # --- 数据迁移结束 ---

    # Drop topic_id from articles table (Auto-generated)
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_topic_id')
        batch_op.drop_constraint('articles_topic_id_fkey', type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add topic_id back to articles table (Auto-generated)
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('articles_topic_id_fkey', 'topics', ['topic_id'], ['id'])
        batch_op.create_index('ix_articles_topic_id', ['topic_id'], unique=False)

    # --- 数据回滚开始 ---
    # 1. 将 posts 表的数据复制回 articles 表
    #    注意: 这里假设回滚时 posts 表还存在
    op.execute("""
        INSERT INTO articles (id, title, content, user_id, topic_id, cover_image, is_published, view_count, created_at, updated_at)
        SELECT id, title, content, user_id, topic_id, cover_image, is_published, view_count, created_at, updated_at
        FROM posts
    """)
    # --- 数据回滚结束 ---

    # Drop posts table (Auto-generated)
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_topic_id'))
        batch_op.drop_index(batch_op.f('ix_posts_title'))

    op.drop_table('posts')
    # ### end Alembic commands ###
