"""Add count fields for posts, articles, and comments

Revision ID: 800d0c54a671
Revises: 2d2b7731a5fc
Create Date: 2025-05-08 11:38:57.587875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800d0c54a671'
down_revision = '2d2b7731a5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_comments_likes_count'), ['likes_count'], unique=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint('post_comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_comments_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_comments_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_post_comments_parent_id_post_comments'), 'post_comments', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_comments_parent_id_post_comments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_post_comments_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('post_comments_parent_id_fkey', 'post_comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key('post_comments_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_likes_count'))
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
