"""Add is_ai_generated to Comment model and integrate AI replies for article comments

Revision ID: 8608a8e9877b
Revises: 87a23b784478
Create Date: 2025-05-14 12:40:13.343690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8608a8e9877b'
down_revision = '87a23b784478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###
