"""Require user_id for original comments and update user info

Revision ID: 877a22405402
Revises: f44a5c313fb9
Create Date: 2025-04-13 01:41:10.732798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877a22405402'
down_revision = 'f44a5c313fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.execute('UPDATE comments SET user_id = 1 WHERE user_id IS NULL')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
