"""Remove original_content_deleted from UserAction

Revision ID: 87a23b784478
Revises: 3a3d4eeb8f58
Create Date: 2025-05-13 23:19:19.806330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a23b784478'
down_revision = '3a3d4eeb8f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_actions_original_content_deleted')
        batch_op.drop_column('original_content_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_content_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_user_actions_original_content_deleted', ['original_content_deleted'], unique=False)

    # ### end Alembic commands ###
