"""Add series fields to Article

Revision ID: 8d14b924c4c2
Revises: 09f6d4a82873
Create Date: 2025-04-12 15:17:31.148467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d14b924c4c2'
down_revision = '09f6d4a82873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('series_order', sa.Integer(), nullable=True))
        batch_op.create_index('ix_article_user_series', ['user_id', 'series_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_series_name'), ['series_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_series_name'))
        batch_op.drop_index('ix_article_user_series')
        batch_op.drop_column('series_order')
        batch_op.drop_column('series_name')

    # ### end Alembic commands ###
