"""Link chat rooms to relationship topics and update relations

Revision ID: 922942102fa9
Revises: e8c35d5a02cc
Create Date: 2025-04-28 19:54:02.786127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922942102fa9'
down_revision = 'e8c35d5a02cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_chat_room_id'), ['chat_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_topic_id', sa.Integer(), nullable=True))
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_chat_rooms_relationship_topic_id'), ['relationship_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_rooms_topic_id'), ['topic_id'], unique=False)
        batch_op.drop_constraint('chat_rooms_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'relationship_topics', ['relationship_topic_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.drop_constraint('relationship_topics_slug_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_relationship_topics_slug'), ['slug'], unique=True)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index('ix_topics_name')
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follows_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_follower_id'), ['follower_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_followed_id'))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_topics_name', ['name'], unique=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('relationship_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_topics_slug'))
        batch_op.create_unique_constraint('relationship_topics_slug_key', ['slug'])
        batch_op.alter_column('slug',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_rooms_topic_id_fkey', 'topics', ['topic_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_chat_rooms_topic_id'))
        batch_op.drop_index(batch_op.f('ix_chat_rooms_relationship_topic_id'))
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('relationship_topic_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_chat_room_id'))

    # ### end Alembic commands ###
