"""Add nickname to User model

Revision ID: 9a2c47557f2d
Revises: 56c1e2868e45
Create Date: 2025-04-12 16:23:42.249816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2c47557f2d'
down_revision = '56c1e2868e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
