"""Add likes to ActionComment

Revision ID: 9a65c18d83d8
Revises: d56889356284
Create Date: 2025-04-30 16:15:33.697196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a65c18d83d8'
down_revision = 'd56889356284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_comment_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['action_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_action_comments_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_comments_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('action_comments_action_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('action_comments_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('action_comments_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user_actions', ['action_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'action_comments', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_article_id_articles', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_comments_article_id_articles', 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('action_comments_parent_id_fkey', 'action_comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key('action_comments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('action_comments_action_id_fkey', 'user_actions', ['action_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_action_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_action_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_action_comments_action_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('action_comment_likes')
    # ### end Alembic commands ###
