"""Add UserFavoriteTopic model and APIs

Revision ID: 9e6a844f0c30
Revises: 2a8f6c140d6b
Create Date: 2025-04-24 01:50:06.343109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6a844f0c30'
down_revision = '2a8f6c140d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_favorite_topic')
    )
    with op.batch_alter_table('user_favorite_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorite_topics_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_favorite_topics_user_id'), ['user_id'], unique=False)

    # 移除对 paragraph_comments 表的修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除对 paragraph_comments 表的修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True)

    with op.batch_alter_table('user_favorite_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorite_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_favorite_topics_topic_id'))

    op.drop_table('user_favorite_topics')
    # ### end Alembic commands ###
