"""Link paragraph comments to articles

Revision ID: a94adaf3ca53
Revises: 1ccaca9f86e9
Create Date: 2025-04-13 00:42:37.872573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94adaf3ca53'
down_revision = '1ccaca9f86e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_id', sa.String(length=255), nullable=False, server_default='legacy-comment'))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_comments_block_identifier')
        batch_op.drop_index('ix_comments_parent_id')
        batch_op.drop_index('ix_comments_tool_id')
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_paragraph_id'), ['paragraph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('comments_tool_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_article_id_articles'), 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('tool_id')
        batch_op.drop_column('block_identifier')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('block_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_parent_id_fkey', 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key('comments_tool_id_fkey', 'tools', ['tool_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_paragraph_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index('ix_comments_article_id')
        batch_op.create_index('ix_comments_tool_id', ['tool_id'], unique=False)
        batch_op.create_index('ix_comments_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_comments_block_identifier', ['block_identifier'], unique=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('paragraph_id')
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###
