"""Add rel topic fav table and chat room constraint

Revision ID: abcdef123456  # 替换为你用的新 ID
Revises: 922942102fa9  # 依赖于已有的迁移
Create Date: 2025-04-28 20:45:00.000000 # 替换为当前时间

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abcdef123456' # 替换为你用的新 ID
down_revision = '922942102fa9' # 依赖于已有的迁移
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted! ###

    # 1. Create user_favorite_relationship_topics table
    op.create_table('user_favorite_relationship_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    # 显式命名外键并设置 ondelete='CASCADE'
    sa.ForeignKeyConstraint(['relationship_topic_id'], ['relationship_topics.id'], name=op.f('fk_user_favorite_relationship_topics_relationship_topic_id_relationship_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorite_relationship_topics_user_id_users'), ondelete='CASCADE'),
    # 显式命名主键
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_favorite_relationship_topics')),
    sa.UniqueConstraint('user_id', 'relationship_topic_id', name='uq_user_favorite_rel_topic')
    )
    # 显式命名索引
    op.create_index(op.f('ix_user_favorite_relationship_topics_relationship_topic_id'), 'user_favorite_relationship_topics', ['relationship_topic_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_relationship_topics_user_id'), 'user_favorite_relationship_topics', ['user_id'], unique=False)

    # 2. Add check constraint ck_chat_room_topic_link to chat_rooms table
    # 这是 922942102fa9 迁移中缺少的约束
    op.create_check_constraint(
        'ck_chat_room_topic_link',
        'chat_rooms',
        '(topic_id IS NOT NULL AND relationship_topic_id IS NULL) OR (topic_id IS NULL AND relationship_topic_id IS NOT NULL)'
    )

    # 注意: 迁移 922942102fa9 已经处理了 chat_rooms 表的列添加、可空性修改、外键和索引。
    # 所以我们这里不再重复这些操作。

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted! ###

    # 1. Drop check constraint ck_chat_room_topic_link from chat_rooms
    op.drop_constraint('ck_chat_room_topic_link', 'chat_rooms', type_='check')

    # 2. Drop user_favorite_relationship_topics table
    op.drop_index(op.f('ix_user_favorite_relationship_topics_user_id'), table_name='user_favorite_relationship_topics')
    op.drop_index(op.f('ix_user_favorite_relationship_topics_relationship_topic_id'), table_name='user_favorite_relationship_topics')
    op.drop_table('user_favorite_relationship_topics')

    # 注意: 922942102fa9 所做更改的回滚应在其自己的 downgrade 函数中处理。

    # ### end Alembic commands ###