"""Remove unique constraint from user_actions

Revision ID: af7a131bb677
Revises: adbf03df96f3
Create Date: 2025-04-17 00:08:21.530260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7a131bb677'
down_revision = 'adbf03df96f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_action_target')
        batch_op.drop_constraint('uq_user_action_target', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_action_target', ['user_id', 'action_type', 'target_type', 'target_id'])
        batch_op.create_index('ix_user_action_target', ['user_id', 'target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###
