"""Re-add icon and slug to Category model

Revision ID: b1339eebd194
Revises: 5d414d0e076e
Create Date: 2025-04-23 19:37:02.259858

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Not used

# revision identifiers, used by Alembic.
revision = 'b1339eebd194'
down_revision = '5d414d0e076e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - KEEP ONLY NECESSARY ###
    print("Applying migration b1339eebd194: Re-add icon and slug to categories table")
    with op.batch_alter_table('categories', schema=None) as batch_op:
        print("Adding icon column to categories table.")
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))
        print("Adding slug column to categories table.")
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        # Optional: Re-add index on slug if needed and if it was actually removed.
        # print("Creating index ix_categories_slug.")
        # batch_op.create_index('ix_categories_slug', ['slug'], unique=True) # Use op.f() if preferred
    print("Finished migration b1339eebd194.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - KEEP ONLY NECESSARY ###
    print("Reverting migration b1339eebd194: Remove icon and slug from categories table")
    with op.batch_alter_table('categories', schema=None) as batch_op:
        # Optional: Drop index first if it was added in upgrade
        # print("Dropping index ix_categories_slug.")
        # batch_op.drop_index('ix_categories_slug') # Use op.f() if preferred
        print("Dropping slug column from categories table.")
        batch_op.drop_column('slug')
        print("Dropping icon column from categories table.")
        batch_op.drop_column('icon')
    print("Finished reverting migration b1339eebd194.")
    # ### end Alembic commands ###
