"""Add reposts_count to UserAction model

Revision ID: b17984d4378e
Revises: 51c44cbd8817
Create Date: 2025-05-12 15:55:54.323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17984d4378e'
down_revision = '51c44cbd8817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加带默认值的列
    op.add_column('user_actions', sa.Column('reposts_count', sa.Integer(), server_default='0', nullable=False))

    # 更新现有记录的转发数
    op.execute("""
        UPDATE user_actions 
        SET reposts_count = COALESCE((
            SELECT COUNT(*) 
            FROM user_actions as reposts
            WHERE reposts.target_type = 'action'
            AND reposts.action_type = 'share'
            AND reposts.target_id = user_actions.id
        ), 0)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_actions', 'reposts_count')
    # ### end Alembic commands ###
