"""Add is_ai_generated to post_comments

Revision ID: d5443a01e27b
Revises: 8608a8e9877b
Create Date: 2025-05-14 13:23:32.780311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5443a01e27b'
down_revision = '8608a8e9877b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###
