"""Add is_deleted column to comments and post_comments tables

Revision ID: d56889356284
Revises: 70a1186f31c1
Create Date: 2025-04-30 14:49:59.914842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56889356284'
down_revision = '70a1186f31c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('comments_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_article_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('comments_article_id_fkey', 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key('comments_parent_id_fkey', 'comments', ['parent_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
