"""添加user_actions表的images字段

Revision ID: de8c63f384b3
Revises: 9a65c18d83d8
Create Date: 2025-05-04 16:32:46.199558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8c63f384b3'
down_revision = '9a65c18d83d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_action_comments_action_id')
        batch_op.drop_index('ix_action_comments_created_at')
        batch_op.drop_index('ix_action_comments_parent_id')
        batch_op.drop_index('ix_action_comments_user_id')
        batch_op.drop_constraint('action_comments_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('action_comments_action_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('action_comments_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_actions', ['action_id'], ['id'])
        batch_op.create_foreign_key(None, 'action_comments', ['parent_id'], ['id'])

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_column('images')

    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('action_comments_parent_id_fkey', 'action_comments', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('action_comments_action_id_fkey', 'user_actions', ['action_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('action_comments_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_action_comments_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_action_comments_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_action_comments_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_action_comments_action_id', ['action_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
