"""Separate paragraph comments and restore original comment model

Revision ID: f44a5c313fb9
Revises: a94adaf3ca53
Create Date: 2025-04-13 01:13:33.893474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44a5c313fb9'
down_revision = 'a94adaf3ca53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('paragraph_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paragraph_comments_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paragraph_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paragraph_comments_paragraph_id'), ['paragraph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paragraph_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_comments_paragraph_id')
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])
        batch_op.drop_column('paragraph_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_id', sa.VARCHAR(length=255), server_default=sa.text("'legacy-comment'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.create_index('ix_comments_paragraph_id', ['paragraph_id'], unique=False)
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paragraph_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_paragraph_comments_paragraph_id'))
        batch_op.drop_index(batch_op.f('ix_paragraph_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_paragraph_comments_article_id'))

    op.drop_table('paragraph_comments')
    # ### end Alembic commands ###
