"""Add chat_rooms and chat_messages tables

Revision ID: f738a196378f
Revises: fd90f7fc728b
Create Date: 2025-04-22 17:20:27.176374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f738a196378f'
down_revision = 'fd90f7fc728b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 首先创建chat_rooms表
    op.create_table('chat_rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('topic_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 然后创建chat_messages表
    op.create_table('chat_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('chat_room_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('is_system_message', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 不需要对现有的表进行修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 首先删除chat_messages表
    op.drop_table('chat_messages')
    
    # 然后删除chat_rooms表
    op.drop_table('chat_rooms')
    
    # 不需要还原paragraph_comments的修改
    # with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
    #     batch_op.alter_column('paragraph_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True)

    # ### end Alembic commands ###
