"""Add ChatRoom and ChatMessage models

Revision ID: fd90f7fc728b
Revises: 10c481e7aa9a
Create Date: 2025-04-22 16:16:05.045537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd90f7fc728b'
down_revision = '10c481e7aa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph_comments', schema=None) as batch_op:
        batch_op.alter_column('paragraph_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
