"""Make posts.topic_id nullable

Revision ID: fe899c2d6bc2
Revises: 73dc42ddc28d
Create Date: 2025-04-24 16:30:57.906071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe899c2d6bc2'
down_revision = '73dc42ddc28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
